name: LinuxBuild

on: [ push ]
jobs:
  generate:
    name: Build all tests & examples
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip build')"
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Install dependence
        run: |
          brew install gcc@11
          sudo apt install -y libopenmpi-dev libhdf5-mpi-dev libhdf5-dev python3-pip python3-sphinx
          python3 -m pip install sphinx-rtd-dark-mode
      - name: Generate
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 \
                -DOPFLOW_WITH_HDF5=ON -DBENCHMARK_ENABLE_TESTING=OFF -DOPFLOW_BUILD_ALL=ON \
                -DOPFLOW_WITH_VTK=OFF ..
          make -j AllTests AllExamples AllBenchmarks
